version: '3.9'

services:
  db:
    image: postgres:14
    container_name: django_postgres
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tu_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - django_net

volumes:
  postgres_data:

networks:
  django_net:
