[tool.black]
line-length = 88
target-version = ['py38']
exclude = '''
/(
    \.venv
  | env
  | venv
  | \.env
  | \.git
  | \.migrations
  | __pycache__
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 88
skip = ["env", "venv", ".env", "__pycache__", "migrations"]

[tool.flake8]
max-line-length = 88
ignore = ["E203", "W503", "E303"]
exclude = ["env", "venv", ".env", "__pycache__", "migrations"]

